# Generated by Django 4.2.21 on 2025-10-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Done', 'Выполнен'), ('In progress', 'В процессе'), ('In delivery', 'На доставке'), ('Raw', 'Не обработан')], db_index=True, default='Raw', max_length=20, verbose_name='статус'),
        ),
    ]
