# Generated by Django 4.2.21 on 2025-10-11 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurantmenuitem',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant', verbose_name='ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Онлайн'), ('Cash', 'Наличными'), ('Card', 'Картой')], db_index=True, default='Cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In progress', 'В процессе'), ('In delivery', 'На доставке'), ('Done', 'Выполнен'), ('Raw', 'Не обработан')], db_index=True, default='Raw', max_length=20, verbose_name='статус'),
        ),
    ]
