# Generated by Django 4.2.21 on 2025-10-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_place_address_place_alter_place_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address_place',
            field=models.CharField(max_length=50, unique=True, verbose_name='адрес'),
        ),
    ]
