# Generated by Django 4.2.21 on 2025-10-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Raw', 'Не обработан'), ('Done', 'Выполнен'), ('In progress', 'В процессе'), ('In delivery', 'На доставке')], db_index=True, default='Raw', max_length=20, verbose_name='статус'),
        ),
    ]
