# Generated by Django 4.2.21 on 2025-10-09 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_comment_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Called at'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivered at'),
        ),
        migrations.AddField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In progress', 'В процессе'), ('Done', 'Выполнен'), ('Raw', 'Не обработан'), ('In delivery', 'На доставке')], db_index=True, default='Raw', max_length=20, verbose_name='статус'),
        ),
    ]
