# Generated by Django 4.2.21 on 2025-10-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Картой'), ('Cash', 'Наличными'), ('Online', 'Онлайн')], db_index=True, default='Cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Done', 'Выполнен'), ('Raw', 'Не обработан'), ('In delivery', 'На доставке'), ('In progress', 'В процессе')], db_index=True, default='Raw', max_length=20, verbose_name='статус'),
        ),
    ]
