# Generated by Django 4.2.21 on 2025-10-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_restaurantmenuitem_managers_order_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Наличными'), ('Online', 'Онлайн'), ('Card', 'Картой')], db_index=True, default='Cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Done', 'Выполнен'), ('In progress', 'В процессе'), ('Raw', 'Не обработан'), ('In delivery', 'На доставке')], db_index=True, default='Raw', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodcartapp.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodcartapp.product'),
        ),
    ]
