# Generated by Django 4.2.21 on 2025-10-14 19:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_payment_method_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurantmenuitem',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Картой'), ('Online', 'Онлайн'), ('Cash', 'Наличными')], db_index=True, default='Cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In delivery', 'На доставке'), ('Raw', 'Не обработан'), ('Done', 'Выполнен'), ('In progress', 'В процессе')], db_index=True, default='Raw', max_length=20, verbose_name='статус'),
        ),
    ]
