# Generated by Django 4.2.21 on 2025-10-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_address_alter_order_called_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Картой'), ('Cash', 'Наличными'), ('Online', 'Онлайн')], db_index=True, max_length=20, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In delivery', 'На доставке'), ('Raw', 'Не обработан'), ('Done', 'Выполнен'), ('In progress', 'В процессе')], db_index=True, default='Raw', max_length=20, verbose_name='статус'),
        ),
    ]
