# Generated by Django 4.2.25 on 2025-11-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Наличными'), ('Online', 'Онлайн'), ('Card', 'Картой')], db_index=True, max_length=20, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In progress', 'В процессе'), ('Done', 'Выполнен'), ('In delivery', 'На доставке'), ('Raw', 'Не обработан')], db_index=True, default='Raw', max_length=20, verbose_name='статус'),
        ),
    ]
