# Generated by Django 4.2.25 on 2025-11-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Онлайн'), ('Card', 'Картой'), ('Cash', 'Наличными')], db_index=True, max_length=20, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In progress', 'В процессе'), ('In delivery', 'На доставке'), ('Done', 'Выполнен'), ('Raw', 'Не обработан')], db_index=True, default='Raw', max_length=20, verbose_name='статус'),
        ),
    ]
